# Link OpenSSL for hardware crypto emulation
ifneq (,$(filter periph_hwcrypto,$(USEMODULE)))
    LINKFLAGS += `pkg-config --libs openssl`
    CFLAGS += `pkg-config --cflags openssl`
endif
ifneq (,$(filter periph_spi,$(USEMODULE)))
  USEMODULE += periph_spidev_linux
endif
ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_native
endif
