#ifndef TESTCASES_H
#define TESTCASES_H

#define PSA_TESTS_LIB_INIT                      "test_c001"

#define PSA_TESTS_KEY_MGMT_IMPORT_KEY           "test_c002"
#define PSA_TESTS_KEY_MGMT_EXPORT_KEY           "test_c003"
#define PSA_TESTS_KEY_MGMT_EXPORT_PUBLIC_KEY    "test_c004"
#define PSA_TESTS_KEY_MGMT_DESTROY_KEY          "test_c005"
#define PSA_TESTS_KEY_MGMT_ATTRIBUTES           "test_c010"
#define PSA_TESTS_KEY_MGMT_COPY_KEY             "test_c044"
#define PSA_TESTS_KEY_MGMT_OPEN_KEY             "test_c050"
#define PSA_TESTS_KEY_MGMT_CLOSE_KEY            "test_c051"

#define PSA_TESTS_MSG_DIG_HASH_COMPUTE          "test_c006"
#define PSA_TESTS_MSG_DIG_HASH_COMPARE          "test_c007"
#define PSA_TESTS_MSG_DIG_HASH_START            "test_c011"
#define PSA_TESTS_MSG_DIG_HASH_UPDATE           "test_c012"
#define PSA_TESTS_MSG_DIG_HASH_VERIFY           "test_c013"
#define PSA_TESTS_MSG_DIG_HASH_FINISH           "test_c014"
#define PSA_TESTS_MSG_DIG_HASH_ABORT            "test_c015"
#define PSA_TESTS_MSG_DIG_HASH_CLONE            "test_c045"

#define PSA_TESTS_KEY_DERIV_SETUP               "test_c008"
#define PSA_TESTS_KEY_DERIV_INPUT_BYTES         "test_c009"
#define PSA_TESTS_KEY_DERIV_INPUT_KEY           "test_c018"
#define PSA_TESTS_KEY_DERIV_KEY_AGREEMENT       "test_c019"
#define PSA_TESTS_KEY_DERIV_OUTPUT_BYTES        "test_c020"
#define PSA_TESTS_KEY_DERIV_OUTPUT_KEY          "test_c021"
#define PSA_TESTS_KEY_DERIV_ABORT               "test_c022"
#define PSA_TESTS_KEY_DERIV_CAPACITY            "test_c023"
#define PSA_TESTS_KEY_DERIV_RAW_AGREEMENT       "test_c043"

#define PSA_TESTS_GENERATION_KEY_GEN            "test_c016"
#define PSA_TESTS_GENERATION_RNG                "test_c017"

#define PSA_TESTS_AEAD_ENCRYPT                  "test_c024"
#define PSA_TESTS_AEAD_DECRYPT                  "test_c025"
#define PSA_TESTS_AEAD_ENCRYPT_SETUP            "test_c052"
#define PSA_TESTS_AEAD_DECRYPT_SETUP            "test_c053"
#define PSA_TESTS_AEAD_GENERATE_NONCE           "test_c054"
#define PSA_TESTS_AEAD_SET_NONCE                "test_c055"
#define PSA_TESTS_AEAD_SET_LENGTH               "test_c056"
#define PSA_TESTS_AEAD_UPDATE_AD                "test_c057"
#define PSA_TESTS_AEAD_UPDATE                   "test_c058"
#define PSA_TESTS_AEAD_FINISH                   "test_c059"
#define PSA_TESTS_AEAD_ABORT                    "test_c060"
#define PSA_TESTS_AEAD_VERIFY                   "test_c061"

#define PSA_TESTS_MAC_SIGN_SETUP                "test_c026"
#define PSA_TESTS_MAC_UPDATE                    "test_c027"
#define PSA_TESTS_MAC_SIGN_FINISH               "test_c028"
#define PSA_TESTS_MAC_VERIFY_SETUP              "test_c029"
#define PSA_TESTS_MAC_VERIFY_FINISH             "test_c030"
#define PSA_TESTS_MAC_ABORT                     "test_c031"
#define PSA_TESTS_MAC_COMPUTE                   "test_c046"
#define PSA_TESTS_MAC_VERIFY                    "test_c047"

#define PSA_TESTS_CIPHER_ENCRYPT_SETUP          "test_c032"
#define PSA_TESTS_CIPHER_DECRYPT_SETUP          "test_c033"
#define PSA_TESTS_CIPHER_GENERATE_IV            "test_c034"
#define PSA_TESTS_CIPHER_SET_IV                 "test_c035"
#define PSA_TESTS_CIPHER_UPDATE                 "test_c036"
#define PSA_TESTS_CIPHER_FINISH                 "test_c037"
#define PSA_TESTS_CIPHER_ABORT                  "test_c038"
#define PSA_TESTS_CIPHER_ENCRYPT                "test_c048"
#define PSA_TESTS_CIPHER_DECRYPT                "test_c049"

#define PSA_TESTS_ASYMMETRIC_ENCRYPT            "test_c039"
#define PSA_TESTS_ASYMMETRIC_DECRYPT            "test_c040"
#define PSA_TESTS_ASYMMETRIC_SIGN_HASH          "test_c041"
#define PSA_TESTS_ASYMMETRIC_VERIFY_HASH        "test_c042"

#endif /* TESTCASES_H */
