INCLUDES += -I$(PKGDIRBASE)/cryptoauthlib
INCLUDES += -I$(PKGDIRBASE)/cryptoauthlib/lib 
INCLUDES += -I$(PKGDIRBASE)/cryptoauthlib/app
INCLUDES += -I$(RIOTBASE)/pkg/cryptoauthlib/include

DIRS += $(RIOTPKG)/cryptoauthlib/contrib