ROM_LEN ?= 0x100000
RAM_LEN ?= 0x2a000

# ROM_START_ADDR ?= 0x00050400
RAM_START_ADDR ?= 0x20016000

FLASHFILE ?= $(BINFILE)

PROGRAMMER ?= jlink
JLINK_DEVICE = NRF9160_XXAA

# Export internal ROM alignment and slot sizes for bootloader support
export MCUBOOT_IMAGE_ALIGN = 8
export IMAGE_HDR_SIZE ?= 0x400
export MCUBOOT_SLOT0_SIZE = 0x50000

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
