ROM_LEN ?= 0x100000
RAM_LEN ?= 0x40000

ifneq (,$(filter trusted_firmware_m,$(USEPKG)))
RAM_LEN = 0x2a000
RAM_START_ADDR ?= 0x20016000

# Export internal ROM alignment and slot sizes for bootloader support
export MCUBOOT_IMAGE_ALIGN = 8
export IMAGE_HDR_SIZE ?= 0x400
export MCUBOOT_SLOT0_SIZE = 0x50000

endif

FLASHFILE ?= $(BINFILE)

PROGRAMMER ?= jlink
JLINK_DEVICE = NRF9160_XXAA

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
